import Image from "next/image";
import { SiteLink as Link } from "./components/site-link";
import { MediaGallery } from "./components/media-gallery";
import { ProductPreview } from "./components/product-preview";
import { ScrollMotion } from "./components/scroll-motion";
import { assetPath, PRODUCT, resourceGroups } from "../lib/site-data";

export default function Home() {
  return <main><ScrollMotion />
    <section className="hero-section">
      <div className="container position-relative"><div className="row align-items-center gy-5">
        <div className="col-lg-5"><span className="eyebrow"><i className="bi bi-windows" /> Feito para assistência técnica</span><h1>Mais bancada. Menos bagunça.</h1><p className="hero-lead">Do aparelho que acabou de entrar à garantia depois da entrega: organize clientes, orçamentos, peças, equipe e documentos em um único sistema.</p><div className="d-flex flex-wrap gap-3 mt-4"><Link className="btn btn-primary btn-lg" href={PRODUCT.purchaseLink}>Ver planos e preços <i className="bi bi-arrow-right" /></Link><a className="btn btn-outline-light btn-lg" href={PRODUCT.trialLink}>Testar grátis por 1 dia</a></div><div className="trust-row"><span><i className="bi bi-shield-check" /> Dados protegidos</span><span><i className="bi bi-wifi-off" /> Operação local</span><span><i className="bi bi-file-earmark-pdf" /> PDFs profissionais</span></div></div>
        <div className="col-lg-7"><div className="hero-console"><div className="shot-top"><span /><span /><span /><small>Loja teste • versão {PRODUCT.version}</small></div><ProductPreview /></div></div>
      </div></div>
    </section>

    <section className="proof-bar"><div className="container"><div><strong>Um fluxo, não telas soltas.</strong><span>Entrada, análise, aprovação, manutenção, retirada e garantia conectadas pelo mesmo histórico.</span></div><div className="proof-stats"><span><strong>9</strong> áreas no passeio</span><span><strong>4</strong> modalidades de licença</span><span><strong>1</strong> base organizada</span></div></div></section>

    <section className="compare-section" data-reveal><div className="container"><div className="section-heading centered"><span className="eyebrow">Mudança prática</span><h2>Saia de registros espalhados para um fluxo consultável.</h2></div><div className="compare-grid"><article className="compare-card before"><span><i className="bi bi-x-circle" /> Antes do sistema</span><ul><li>Anotações, conversas e documentos em lugares diferentes</li><li>Consulta demorada de atendimentos anteriores</li><li>Orçamentos e termos feitos manualmente</li><li>Pendências lembradas apenas pela equipe</li></ul></article><article className="compare-card after"><span><i className="bi bi-check-circle" /> Com o sistema</span><ul><li>Cliente, aparelho, serviço e documentos conectados</li><li>Pesquisa por contato, equipamento, IMEI ou protocolo</li><li>PDFs padronizados com os dados já registrados</li><li>Alertas, filtros e painéis para o que exige atenção</li></ul></article></div></div></section>

    <section className="buy-band"><div className="container"><div><span>Veja sua assistência por inteiro</span><strong>Uma licença. Todos os recursos. Sem módulos escondidos.</strong></div><Link className="btn btn-primary" href={PRODUCT.purchaseLink}>Comparar licenças <i className="bi bi-arrow-right" /></Link></div></section>

    <section className="section-light" id="problema" data-reveal><div className="container"><div className="section-heading centered"><span className="eyebrow">Menos improviso</span><h2>O que costuma se perder, passa a ter lugar certo.</h2><p>O sistema acompanha o trabalho real da assistência sem exigir que a equipe monte controles paralelos.</p></div><div className="row g-4 mt-2">{[
      ["bi-chat-left-dots", "Aprovações e contatos", "Guarde quem aprovou, por qual canal e qual número deve receber a mensagem."],
      ["bi-phone-vibrate", "Aparelhos e vínculos", "Veja cada aparelho do cliente, inclusive compras, vendas e atendimentos conjuntos."],
      ["bi-clock-history", "Prazos e pendências", "Destaque análises, peças, garantias, pagamentos e retiradas que precisam de atenção."],
      ["bi-journal-check", "Documentação", "Gere PDFs padronizados e mantenha os documentos recentes acessíveis."],
    ].map(([icon,title,text]) => <div className="col-sm-6 col-lg-3" key={title}><article className="benefit-card h-100"><i className={`bi ${icon}`} /><h3>{title}</h3><p>{text}</p></article></div>)}</div></div></section>

    <section className="section-dark" data-reveal><div className="container"><div className="section-heading"><span className="eyebrow">Tudo no lugar certo</span><h2>Do balcão à gestão, sem perder o contexto.</h2><p>Escolha uma área e veja como ela ajuda no atendimento, na bancada e na administração da loja.</p></div><div className="feature-grid mt-5">{resourceGroups.slice(0,6).map((group) => <article className="feature-tile" key={group.id}><div className="feature-icon"><i className={`bi ${group.icon}`} /></div><div><span>{group.kicker}</span><h3>{group.title}</h3><p>{group.summary}</p></div></article>)}</div><div className="text-center mt-5 d-flex flex-wrap justify-content-center gap-3"><Link className="btn btn-outline-light btn-lg" href="/recursos">Explorar todos os recursos</Link><Link className="btn btn-primary btn-lg" href={PRODUCT.purchaseLink}>Quero para minha assistência</Link></div></div></section>

    <section className="workflow-section"><div className="container"><div className="section-heading centered"><span className="eyebrow">Fluxo conectado</span><h2>Uma sequência clara para a equipe inteira.</h2></div><div className="workflow-line">{[
      ["01","Receber","Cliente, aparelho e relato"],["02","Analisar","Técnico, diagnóstico e peças"],["03","Aprovar","Versão, canal e responsável"],["04","Executar","Manutenção e andamento"],["05","Entregar","Pagamento, retirada e garantia"],
    ].map(([n,title,text]) => <div className="workflow-step" key={n}><span>{n}</span><i className="bi bi-check-lg" /><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>

    <section className="differentials-section"><div className="container"><div className="row g-4"><div className="col-lg-6"><article className="differential-card guarantee"><div className="differential-icon"><i className="bi bi-shield-check" /></div><span className="eyebrow">Diferencial de pós-atendimento</span><h2>Garantia vinculada ao serviço que realmente foi feito.</h2><p>A garantia nasce do orçamento finalizado, mantém cliente e aparelho, identifica prazo, avaliação, decisão, andamento e responsável. No fim, a loja pode gerar o comprovante correspondente.</p><ul className="check-list"><li>Pesquisa por cliente, aparelho, IMEI, orçamento ou número</li><li>Histórico de mudanças e responsáveis</li><li>Exclusão controlada quando criada incorretamente</li><li>Pasta conjunta para produtos vinculados, com obrigações separadas</li></ul><Link className="text-link" href="/guia#garantias">Ver como utilizar <i className="bi bi-arrow-right" /></Link></article></div><div className="col-lg-6"><article className="differential-card transfer"><div className="differential-icon"><i className="bi bi-arrow-left-right" /></div><span className="eyebrow">Diferencial operacional</span><h2>Transferência de dados com origem, destino e conferência.</h2><p>A ficha própria registra os dois aparelhos, identificadores, números, contas, tipos de dados autorizados e verificações antes da entrega. Campos vazios são omitidos do PDF.</p><ul className="check-list"><li>Aparelho de origem e aparelho de destino</li><li>WhatsApp, chip/eSIM, backup e autenticação em duas etapas</li><li>Autorização separada para apagar o aparelho antigo</li><li>Credenciais temporárias, não gravadas no cadastro</li></ul><Link className="text-link" href="/guia#transferencia">Ver como utilizar <i className="bi bi-arrow-right" /></Link></article></div></div></div></section>

    <section className="owner-tour" id="demonstracao" data-reveal><div className="container"><div className="section-heading centered"><span className="eyebrow">O que o dono precisa enxergar</span><h2>Veja como o sistema organiza a rotina da loja.</h2><p>Da visão geral ao cadastro do orçamento, cada tela foi pensada para encontrar o que importa sem perder tempo.</p></div><div className="real-screen-grid">{[
      ["inicio-real.png", "Visão geral", "Faturamento, andamento, estoque, garantias e o que exige atenção agora."],
      ["historico-real.png", "Histórico", "Filtros, atendimentos vinculados e todos os estados da assistência."],
      ["clientes-real.png", "Clientes", "Pesquisa preparada para milhares de registros, aparelhos e atendimentos."],
      ["novo-orcamento-real.png", "Novo orçamento", "Cadastro completo com sugestões, revisão e número público."],
    ].map(([file,title,caption]) => <figure className="real-screen-card" key={file}><div><Image src={assetPath(`/assets/img/app/${file}`)} width={1440} height={900} alt={`Tela do aplicativo: ${title}`} sizes="(max-width: 767px) 100vw, 50vw" /></div><figcaption><strong>{title}</strong><span>{caption}</span><small><i className="bi bi-check-circle" /> Disponível na versão {PRODUCT.version}</small></figcaption></figure>)}</div><div className="tour-action"><p>Quer ver como isso se encaixa na rotina da sua loja?</p><a className="btn btn-primary btn-lg" href={PRODUCT.trialLink}>Solicitar teste grátis <i className="bi bi-whatsapp" /></a></div></div></section>

    <section className="section-light" data-reveal><div className="container"><div className="section-heading centered"><span className="eyebrow">Documentos que valorizam sua entrega</span><h2>Sua loja com uma apresentação mais profissional.</h2><p>Abra os exemplos e veja como orçamento, retirada, compra e fichas ficam prontos para entregar ao cliente.</p></div><div className="mt-5"><MediaGallery /></div></div></section>

    <section className="security-section"><div className="container"><div className="security-card"><div><span className="eyebrow">Proteção e continuidade</span><h2>O banco da loja continua sob controle da loja.</h2><p>O aplicativo usa banco SQLite local criptografado, backups autenticados, usuários com permissões, auditoria e atualizações assinadas.</p><div className="security-points"><span><i className="bi bi-database-lock" /> Banco local criptografado</span><span><i className="bi bi-person-lock" /> Acessos individuais</span><span><i className="bi bi-cloud-check" /> Sincronização protegida quando aplicável</span><span><i className="bi bi-arrow-repeat" /> Atualização assinada</span></div></div><Link className="btn btn-primary btn-lg" href="/privacidade">Como os dados são tratados</Link></div></div></section>

    <section className="updates-section"><div className="container"><div className="section-heading"><span className="eyebrow">Atualizações e melhorias</span><h2>A versão {PRODUCT.version} deixa a rotina mais segura e previsível.</h2><p>Os ajustes mais recentes cuidam dos documentos, do preenchimento e da navegação diária.</p></div><div className="updates-grid">{[
      ["bi-file-earmark-text","Termos mais claros","A ordem de serviço informa os prazos de 30 e 90 dias, incluindo o aviso e a autorização assinada pelo cliente."],
      ["bi-file-earmark-pdf","PDFs bem divididos","Valores permanecem reunidos na primeira página, sem separar um mesmo bloco entre páginas."],
      ["bi-search","Cadastro mais rápido","A marca sugere opções conhecidas conforme o tipo de aparelho e as primeiras letras digitadas."],
      ["bi-keyboard","Navegação pelo teclado","A tecla Esc retorna ao menu anterior e os campos obrigatórios conduzem a ação de prosseguir."],
      ["bi-clock","Tempos mais fiéis","Manutenções podem registrar menos de uma hora, respeitando o mínimo de 15 minutos e ignorando fluxos que não passaram pela bancada."],
      ["bi-shield-lock","Dados mais consistentes","Garantias, licenças e registros de demonstração seguem regras próprias para evitar informações duplicadas ou fora de contexto."],
    ].map(([icon,title,text]) => <article key={title}><i className={`bi ${icon}`} /><h3>{title}</h3><p>{text}</p></article>)}</div><Link className="text-link" href="/guia#atualizacoes">Como funcionam licença e atualizações <i className="bi bi-arrow-right" /></Link></div></section>

    <section className="final-cta"><div className="container"><div className="cta-panel"><span className="eyebrow">Versão {PRODUCT.version}</span><h2>Organize hoje o próximo aparelho que entrar na sua loja.</h2><p>Todos os planos incluem os mesmos recursos. Você também pode experimentar o sistema gratuitamente por 1 dia.</p><div className="d-flex flex-wrap justify-content-center gap-3"><Link className="btn btn-primary btn-lg" href={PRODUCT.purchaseLink}>Ver licenças</Link><a className="btn btn-outline-light btn-lg" href={PRODUCT.trialLink}>Teste grátis de 1 dia</a></div></div></div></section>
  </main>;
}
