import Link from "next/link";
import { MediaGallery } from "./components/media-gallery";
import { ProductPreview } from "./components/product-preview";
import { ScrollMotion } from "./components/scroll-motion";
import { PRODUCT, resourceGroups } from "../lib/site-data";

export default function Home() {
  return <main><ScrollMotion />
    <section className="hero-section">
      <div className="container position-relative"><div className="row align-items-center gy-5">
        <div className="col-lg-5"><span className="eyebrow"><i className="bi bi-windows" /> Feito para assistência técnica</span><h1>Mais bancada. Menos bagunça.</h1><p className="hero-lead">Do aparelho que acabou de entrar à garantia depois da entrega: organize clientes, orçamentos, peças, equipe e documentos em um único sistema.</p><div className="d-flex flex-wrap gap-3 mt-4"><Link className="btn btn-primary btn-lg" href={PRODUCT.purchaseLink}>Quero organizar minha loja <i className="bi bi-whatsapp" /></Link><Link className="btn btn-outline-light btn-lg" href="#demonstracao">Ver o sistema</Link></div><div className="trust-row"><span><i className="bi bi-shield-check" /> Dados protegidos</span><span><i className="bi bi-wifi-off" /> Operação local</span><span><i className="bi bi-file-earmark-pdf" /> PDFs profissionais</span></div></div>
        <div className="col-lg-7"><div className="hero-console"><div className="shot-top"><span /><span /><span /><small>Loja teste • versão {PRODUCT.version}</small></div><ProductPreview /></div></div>
      </div></div>
    </section>

    <section className="proof-bar"><div className="container"><div><strong>Um fluxo, não telas soltas.</strong><span>Entrada, análise, aprovação, manutenção, retirada e garantia conectadas pelo mesmo histórico.</span></div><div className="proof-stats"><span><strong>8</strong> áreas de gestão</span><span><strong>4</strong> modalidades de licença</span><span><strong>1</strong> base organizada</span></div></div></section>

    <section className="compare-section" data-reveal><div className="container"><div className="section-heading centered"><span className="eyebrow">Mudança prática</span><h2>Saia de registros espalhados para um fluxo consultável.</h2></div><div className="compare-grid"><article className="compare-card before"><span><i className="bi bi-x-circle" /> Antes do sistema</span><ul><li>Anotações, conversas e documentos em lugares diferentes</li><li>Consulta demorada de atendimentos anteriores</li><li>Orçamentos e termos feitos manualmente</li><li>Pendências lembradas apenas pela equipe</li></ul></article><article className="compare-card after"><span><i className="bi bi-check-circle" /> Com o sistema</span><ul><li>Cliente, aparelho, serviço e documentos conectados</li><li>Pesquisa por contato, equipamento, IMEI ou protocolo</li><li>PDFs padronizados com os dados já registrados</li><li>Alertas, filtros e painéis para o que exige atenção</li></ul></article></div></div></section>

    <section className="buy-band"><div className="container"><div><span>Veja sua assistência por inteiro</span><strong>Uma licença. Todos os recursos. Sem módulos escondidos.</strong></div><Link className="btn btn-primary" href={PRODUCT.purchaseLink}>Falar no WhatsApp <i className="bi bi-whatsapp" /></Link></div></section>

    <section className="section-light" id="problema" data-reveal><div className="container"><div className="section-heading centered"><span className="eyebrow">Menos improviso</span><h2>O que costuma se perder, passa a ter lugar certo.</h2><p>O sistema acompanha o trabalho real da assistência sem exigir que a equipe monte controles paralelos.</p></div><div className="row g-4 mt-2">{[
      ["bi-chat-left-dots", "Aprovações e contatos", "Guarde quem aprovou, por qual canal e qual número deve receber a mensagem."],
      ["bi-phone-vibrate", "Aparelhos e vínculos", "Veja cada aparelho do cliente, inclusive compras, vendas e atendimentos conjuntos."],
      ["bi-clock-history", "Prazos e pendências", "Destaque análises, peças, garantias, pagamentos e retiradas que precisam de atenção."],
      ["bi-journal-check", "Documentação", "Gere PDFs padronizados e mantenha os documentos recentes acessíveis."],
    ].map(([icon,title,text]) => <div className="col-sm-6 col-lg-3" key={title}><article className="benefit-card h-100"><i className={`bi ${icon}`} /><h3>{title}</h3><p>{text}</p></article></div>)}</div></div></section>

    <section className="section-dark" data-reveal><div className="container"><div className="section-heading"><span className="eyebrow">Recursos reais</span><h2>Do balcão à gestão, sem perder o contexto.</h2><p>Cada módulo abaixo existe na versão atual e foi conferido diretamente no aplicativo e em sua documentação interna.</p></div><div className="feature-grid mt-5">{resourceGroups.slice(0,6).map((group) => <article className="feature-tile" key={group.id}><div className="feature-icon"><i className={`bi ${group.icon}`} /></div><div><span>{group.kicker}</span><h3>{group.title}</h3><p>{group.summary}</p></div></article>)}</div><div className="text-center mt-5 d-flex flex-wrap justify-content-center gap-3"><Link className="btn btn-outline-light btn-lg" href="/recursos">Explorar todos os recursos</Link><Link className="btn btn-primary btn-lg" href={PRODUCT.purchaseLink}>Quero para minha assistência</Link></div></div></section>

    <section className="workflow-section"><div className="container"><div className="section-heading centered"><span className="eyebrow">Fluxo conectado</span><h2>Uma sequência clara para a equipe inteira.</h2></div><div className="workflow-line">{[
      ["01","Receber","Cliente, aparelho e relato"],["02","Analisar","Técnico, diagnóstico e peças"],["03","Aprovar","Versão, canal e responsável"],["04","Executar","Manutenção e andamento"],["05","Entregar","Pagamento, retirada e garantia"],
    ].map(([n,title,text]) => <div className="workflow-step" key={n}><span>{n}</span><i className="bi bi-check-lg" /><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>

    <section className="differentials-section"><div className="container"><div className="row g-4"><div className="col-lg-6"><article className="differential-card guarantee"><div className="differential-icon"><i className="bi bi-shield-check" /></div><span className="eyebrow">Diferencial de pós-atendimento</span><h2>Garantia vinculada ao serviço que realmente foi feito.</h2><p>A garantia nasce do orçamento finalizado, mantém cliente e aparelho, identifica prazo, avaliação, decisão, andamento e responsável. No fim, a loja pode gerar o comprovante correspondente.</p><ul className="check-list"><li>Pesquisa por cliente, aparelho, IMEI, orçamento ou número</li><li>Histórico de mudanças e responsáveis</li><li>Exclusão controlada quando criada incorretamente</li><li>Pasta conjunta para produtos vinculados, com obrigações separadas</li></ul><Link className="text-link" href="/guia#garantias">Ver como utilizar <i className="bi bi-arrow-right" /></Link></article></div><div className="col-lg-6"><article className="differential-card transfer"><div className="differential-icon"><i className="bi bi-arrow-left-right" /></div><span className="eyebrow">Diferencial operacional</span><h2>Transferência de dados com origem, destino e conferência.</h2><p>A ficha própria registra os dois aparelhos, identificadores, números, contas, tipos de dados autorizados e verificações antes da entrega. Campos vazios são omitidos do PDF.</p><ul className="check-list"><li>Aparelho de origem e aparelho de destino</li><li>WhatsApp, chip/eSIM, backup e autenticação em duas etapas</li><li>Autorização separada para apagar o aparelho antigo</li><li>Credenciais temporárias, não gravadas no cadastro</li></ul><Link className="text-link" href="/guia#transferencia">Ver como utilizar <i className="bi bi-arrow-right" /></Link></article></div></div></div></section>

    <section className="owner-tour" id="demonstracao" data-reveal><div className="container"><div className="section-heading centered"><span className="eyebrow">O que o dono precisa enxergar</span><h2>Do atendimento ao resultado, sem procurar informação.</h2><p>Exemplos com dados fictícios mostram as telas que mais ajudam a decidir, cobrar e acompanhar a equipe.</p></div><div className="owner-screen-grid">
      <article className="owner-screen history-screen"><div className="owner-screen-head"><span><i className="bi bi-clock-history" /> Histórico</span><small>44 registros</small></div><div className="fake-search"><i className="bi bi-search" /> Buscar cliente, telefone, aparelho ou IMEI</div><div className="status-row"><span>Todos</span><span className="blue">Em manutenção</span><span className="green">Pronto</span></div>{[["ORC-20260822-0040","Marina Alves","Galaxy S23","Em manutenção"],["ORC-20260822-0039","Carlos Henrique","iPhone 13","Aguardando aprovação"],["ORC-20260821-0038","Ana Beatriz","Moto G84","Pronto para retirada"]].map(([id,name,device,status]) => <div className="quote-row" key={id}><div><small>{id}</small><strong>{name}</strong><em>{device}</em></div><span>{status}</span></div>)}</article>
      <article className="owner-screen clients-screen"><div className="owner-screen-head"><span><i className="bi bi-people" /> Clientes</span><small>Base organizada</small></div><div className="fake-search active"><i className="bi bi-search" /> Roberta</div><div className="filter-pills"><span>Com CPF</span><span>Com aparelho</span><span>Ativos</span></div><div className="client-result"><span>RF</span><div><strong>Roberta F. Ferreira Garcia</strong><small>(16) 99999-7788 • 2 aparelhos</small></div><i className="bi bi-chevron-right" /></div><div className="device-lines"><span><i className="bi bi-phone" /> Samsung Galaxy S22 <b>Orçamento</b></span><span><i className="bi bi-phone" /> Apple iPhone 15 <b>Vendido</b></span></div></article>
      <article className="owner-screen stock-screen"><div className="owner-screen-head"><span><i className="bi bi-phone" /> Aparelhos</span><small>Estoque e comércio</small></div><div className="stock-summary"><span><b>8</b> disponíveis</span><span><b>3</b> em análise</span><span><b>5</b> vendidos</span></div><div className="device-card"><i className="bi bi-phone" /><div><strong>Apple iPhone 13 • 128 GB</strong><small>Seminovo • Preto • bateria 88%</small></div><span>R$ 2.590</span></div><div className="device-card"><i className="bi bi-phone" /><div><strong>Samsung Galaxy S23 Ultra</strong><small>Novo • PayJoy • 256 GB</small></div><span>R$ 3.890</span></div><div className="owner-insight"><i className="bi bi-graph-up-arrow" /><span><strong>Decisões mais rápidas</strong> Custo, estado e valor visíveis no mesmo lugar.</span></div></article>
    </div><div className="tour-action"><p>Quer ver como isso se encaixa na rotina da sua loja?</p><Link className="btn btn-primary btn-lg" href={PRODUCT.purchaseLink}>Conversar pelo WhatsApp <i className="bi bi-whatsapp" /></Link></div></div></section>

    <section className="section-light" data-reveal><div className="container"><div className="section-heading centered"><span className="eyebrow">Documentos que valorizam sua entrega</span><h2>Sua loja com uma apresentação mais profissional.</h2><p>Todos os exemplos abaixo foram gerados pelo aplicativo com “Loja teste” e dados fictícios de validação. Clique para ampliar.</p></div><div className="mt-5"><MediaGallery /></div></div></section>

    <section className="security-section"><div className="container"><div className="security-card"><div><span className="eyebrow">Proteção e continuidade</span><h2>O banco da loja continua sob controle da loja.</h2><p>O aplicativo usa banco SQLite local criptografado, backups autenticados, usuários com permissões, auditoria e atualizações assinadas.</p><div className="security-points"><span><i className="bi bi-database-lock" /> Banco local criptografado</span><span><i className="bi bi-person-lock" /> Acessos individuais</span><span><i className="bi bi-cloud-check" /> Sincronização protegida quando aplicável</span><span><i className="bi bi-arrow-repeat" /> Atualização assinada</span></div></div><Link className="btn btn-primary btn-lg" href="/privacidade">Como os dados são tratados</Link></div></div></section>

    <section className="updates-section"><div className="container"><div className="section-heading"><span className="eyebrow">Atualizações e melhorias</span><h2>A versão 8.0.1 consolidou detalhes que evitam retrabalho.</h2><p>A evolução recente foi traduzida em benefícios visíveis para quem atende, executa e administra.</p></div><div className="updates-grid">{[
      ["bi-arrow-repeat","Atualização mais confiável","Download automático assinado, canais estável e beta e passagem corrigida da beta para a versão oficial."],
      ["bi-clock","Tempos mais fiéis","Manutenções podem registrar menos de uma hora, respeitando o mínimo de 15 minutos e ignorando fluxos que não passaram pela bancada."],
      ["bi-ui-checks-grid","Interface padronizada","Tema claro menos cansativo, menus azuis consistentes, modais roláveis e formulários mais previsíveis pelo teclado."],
      ["bi-person-vcard","Cadastros mais práticos","Autocompletar em áreas operacionais, nome com primeiro e segundo termo e aparelhos comprados ou vendidos no perfil."],
      ["bi-tags","Mais controle comercial","Desconto para aprovações antigas, agrupamento de compras por status e PayJoy como estado comercial do aparelho."],
      ["bi-shield-lock","Correções de integridade","Renovação preserva a empresa, exclusão de garantia remove referências e dados de demonstração não entram na sincronização."],
    ].map(([icon,title,text]) => <article key={title}><i className={`bi ${icon}`} /><h3>{title}</h3><p>{text}</p></article>)}</div><Link className="text-link" href="/guia#atualizacoes">Como funcionam licença e atualizações <i className="bi bi-arrow-right" /></Link></div></section>

    <section className="final-cta"><div className="container"><div className="cta-panel"><span className="eyebrow">Versão {PRODUCT.version}</span><h2>Organize hoje o próximo aparelho que entrar na sua loja.</h2><p>Todos os planos incluem os mesmos recursos. Escolha apenas o período de licença mais adequado.</p><div className="d-flex flex-wrap justify-content-center gap-3"><Link className="btn btn-primary btn-lg" href={PRODUCT.purchaseLink}>Ver licenças</Link><Link className="btn btn-outline-light btn-lg" href="/guia">Conhecer o guia</Link></div></div></div></section>
  </main>;
}
