import type { Metadata } from "next";
import { SiteLink as Link } from "../components/site-link";
import { PageHero } from "../components/page-hero";
import { ProductPreview } from "../components/product-preview";
import { PRODUCT, resourceGroups } from "../../lib/site-data";

export const metadata: Metadata = { title: "Recursos da versão 8.2 | Assistência Simplificada", description: "Conheça Atendimentos, clientes, peças, aparelhos, garantias, gestão, documentos, backup e segurança no aplicativo.", alternates: { canonical: "/recursos" } };

const guideLinks: Record<string, string> = { orcamentos: "novo-orcamento", clientes: "clientes", operacao: "manutencao", garantias: "garantias", aparelhos: "compra-venda", documentos: "documentos", gestao: "indicadores", seguranca: "backup" };

export default function RecursosPage() { return <main><PageHero eyebrow="Visão completa" title="Recursos que acompanham a operação de verdade." description="Do atendimento à gestão, cada área foi pensada para reduzir repetição e manter a equipe alinhada." /><section className="section-light"><div className="container"><nav className="resource-index" aria-label="Índice de recursos">{resourceGroups.map((group) => <a key={group.id} href={`#${group.id}`}><i className={`bi ${group.icon}`} />{group.title}</a>)}</nav><div className="resource-sections">{resourceGroups.map((group,index) => <article id={group.id} className="resource-detail" key={group.id}><div className="resource-detail-copy"><span className="eyebrow">{group.kicker}</span><h2>{group.title}</h2><p>{group.summary}</p><ul className="check-list dark">{group.items.map((item) => <li key={item}>{item}</li>)}</ul><Link className="text-link" href={`/guia#${guideLinks[group.id]}`}>Ver como utilizar <i className="bi bi-arrow-right" /></Link></div><div className="resource-visual" aria-hidden="true"><span className="resource-number">{String(index+1).padStart(2,"0")}</span><i className={`bi ${group.icon}`} /><small>Disponível na versão {PRODUCT.version}</small></div></article>)}</div><section className="micro-inventory"><div className="section-heading centered"><span className="eyebrow">Conheça todos os recursos</span><h2>Microfunções que também economizam tempo.</h2><p>Detalhes pequenos na interface que reduzem digitação, repetição e dúvida durante o atendimento.</p></div><div className="micro-grid">{[
        ["Cadastro e validação",["Autocompletar clientes","Máscaras de telefone e documento","Primeiro e segundo nome obrigatórios","Limites seguros de texto","Valores em moeda com foco padronizado","Sugestão de serviço pelo relato"]],
        ["Pesquisa e organização",["Busca por protocolo, contato e aparelho","Filtros persistentes de status","Ordenação por atualização, criação, valor ou status","Paginação compartilhada","Nomes longos abreviados somente na lista","Orçamentos vinculados mantidos próximos"]],
        ["Ações e documentos",["Editar, duplicar, arquivar e excluir com confirmação","PDF, impressão e mensagem","Downloads automáticos","Escolha do número de contato","Prévia e central de documentos","Comprovantes próprios de compra e venda"]],
        ["Preferências e controle",["Tema claro ou noturno","Pasta de documentos configurável","Inicialização com o Windows","Menus exclusivos e modais roláveis","Atalhos de teclado e tutoriais","Templates de mensagens e dados da empresa"]],
      ].map(([title,items]) => <details key={title as string}><summary>{title as string}<i className="bi bi-plus-lg" /></summary><ul>{(items as string[]).map((item) => <li key={item}>{item}</li>)}</ul></details>)}</div></section></div></section><section className="showcase-section"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-8"><div className="hero-console resource-console"><div className="shot-top"><span /><span /><span /><small>Loja teste • versão {PRODUCT.version}</small></div><ProductPreview /></div></div><div className="col-lg-4"><span className="eyebrow">Navegação atual</span><h2>Todos os setores da assistência no mesmo lugar.</h2><p>Operação, negócio e gestão ficam reunidos da entrada do aparelho ao backup.</p><Link className="btn btn-primary" href="/guia#novo-orcamento">Aprender a criar um orçamento</Link></div></div></div></section><section className="final-cta"><div className="container"><div className="cta-panel"><h2>Os mesmos recursos em todos os planos.</h2><p>A modalidade muda apenas o período da licença.</p><Link className="btn btn-primary btn-lg" href={PRODUCT.purchaseLink}>Comparar licenças</Link></div></div></section></main>; }
